### CREAR PRODUCTO
POST http://localhost:7878/v1/api/product/save
Content-Type: application/json

{
  "name": "Book",
  "price": 250.50
}

### LISTAR PRODUCTO
GET http://localhost:7878/v1/api/product/all
Accept: application/json

### ACTUALIZAR PRODUCTO
PUT http://localhost:7878/v1/api/product?productId=1
Accept: application/json

