server:
  port: 8181
spring:
  application:
    name: ms-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: service-customer
          uri: lb://MS-CUSTOMER
          predicates:
            - Path=/ms-customer/**
          filters:
            - RewritePath=/ms-customer/(?<remaining>.*), /$\{remaining}
        - id: service_product
          uri: lb://MS-PRODUCT
          predicates:
            - Path=/ms-product/**
          filters:
            - RewritePath=/ms-product/(?<remaining>.*), /$\{remaining}
   #   discovery:
    #    locator:
    #      enabled: true
     #     lower-case-service-id: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"


