server:
  port: 8181
spring:
  application:
    name: ms-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka


