spring:
  application:
    name: ms-customer
  h2:
    console:
      enabled: true
  zipkin:
      enabled: false
  #base-url: http://localhost:9411

server:
  port: ${SERVER_PORT:6945}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}
management:
  endpoints:
    web:
      exposure:
        include: "*"
#arquitectura:
 # software: "GITHUB refresh"
