spring:
  application:
    name: ms-sale
  h2:
    console:
      enabled: true
  zipkin:
    base-url: http://localhost:9411
server:
  port: ${SERVERPORT:8743}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}

