version: "2.4"

networks:
  arquitectura:
    name: network-projects
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1

  software:
    name: network-config-server
    external: true
services:
  ms-discovery:
    image: ms-discovery:0.0.1
    mem_limit: 150m
    ports:
      - "8762:8762"
    networks:
      - software
      - arquitectura
  #      environment:
#        - "EUREKA_URI=http://192.168.0.159:8762/eureka"
  ms-customer:
    image: ms-customer:0.0.3
    mem_limit: 200m
    networks:
      - software
      - arquitectura
  #  ports:
  #    - "6945:6945"
    environment:
      - "EUREKA_URI=http://192.168.65.5:8762/eureka"
      -  "CONFIG_URI=http://ms-config-server:8889"
    volumes:
      - "/opt/local/logs:/opt/arquitectura/logs"
    depends_on:
      ms-discovery:
        condition: service_started
